#!/bin/bash

repos="/home/aaron/plugins/plugin-utilities/repos"
tx_dir="/home/aaron/plugins/.tx"
tx_file="${tx_dir}/config"

if [ ! -d "${tx_dir}" ]; then
  mkdir -p "${tx_dir}"
fi

cat <<EOF > ${tx_file}
[main]
host = https://www.transifex.com
lang_map = de: de_DE, it: it_IT, ru: ru_RU, uk: uk_UK, da: da_DA, no: no_NO, sv: sv_SV
type = PO
EOF

while read repo; do

  cat <<EOF >> ${tx_file}
[${repo}.${repo}pot]
file_filter = ${repo}/usr/share/openmediavault/locale/<lang>/${repo}.po
source_file = ${repo}/usr/share/openmediavault/locale/${repo}.pot
source_lang = en

EOF

done < ${repos}
