#!/bin/bash

location="/home/aaron/plugins/"
subdir="${location}plugin-utilities/"
repos="${subdir}repos"
other="${subdir}other"
tx_dir="${location}.tx"
tx_file="${tx_dir}/config"

if [ ! -d "${tx_dir}" ]; then
  mkdir -p "${tx_dir}"
fi

cat <<EOF > ${tx_file}
[main]
host = https://www.transifex.com
lang_map = de: de_DE, it: it_IT, ru: ru_RU, uk: uk_UK, da: da_DA, no: no_NO, sv: sv_SV
type = PO

EOF

# repos
while read repo; do

  cat <<EOF >> ${tx_file}
[${repo}.${repo}pot]
file_filter = ${repo}/usr/share/openmediavault/locale/<lang>/${repo}.po
source_file = ${repo}/usr/share/openmediavault/locale/${repo}.pot
source_lang = en

EOF

done < ${repos}

# other repos
while read repo; do

  project=$(echo ${repo} | cut -f2 -d/)

  cat <<EOF >> ${tx_file}
[${project}.${project}pot]
file_filter = ${project}/usr/share/openmediavault/locale/<lang>/${project}.po
source_file = ${project}/usr/share/openmediavault/locale/${project}.pot
source_lang = en

EOF

done < ${other}
