#!/bin/bash

# change to code directory
cd /home/aaron/code/openmediavault-code

# get current revision
revision=$(svn info | grep "Revision:" | cut -f2 -d":" | tr -d " ")

# update svn repo and get new revision
svn update
newrevision=$(svn info | grep "Revision:" | cut -f2 -d":" | tr -d " ")

if [ $revision != $newrevision ]; then
  # add changed files to git
  git add $(git ls-files --modified)

  # remove deleted files
  git rm $(git ls-files --deleted)

  # create commit
  git commit -m "update to revision $newrevision"

  # push to github
  git push

  echo "Updated to $newrevision" >> /home/aaron/omv.log
else
  echo "No updates." >> /home/aaron/omv.log
fi
