#!/bin/bash

clean=$1

location="/home/aaron/plugins/"
subdir="${location}plugin-utilities/"
repos="${subdir}repos"
misc="${subdir}misc"
other="${subdir}other"
omv_code="openmediavault-code"
developer="OpenMediaVault-Plugin-Developers"

# plugins
while read repo; do

  echo ${repo}

  if [ "${clean}" = "clean" ] || [ "${clean}" = "${repo}" ]; then
    rm -rf "${location}${repo}"
  fi

  if [ ! -d "${location}${repo}" ]; then
    cd ${location}
    git clone https://github.com/${developer}/${repo}.git
  else
    cd ${location}${repo}
    git pull
  fi

  cd ${location}${repo}
  git status

done < ${repos}

# misc repos
while read repo; do

  echo ${repo}

  if [ "${clean}" = "clean" ] || [ "${clean}" = "${repo}" ]; then
    rm -rf "${location}${repo}"
  fi

  if [ ! -d "${location}${repo}" ]; then
    cd ${location}
    git clone https://github.com/${developer}/${repo}.git
  else
    cd ${location}${repo}
    git pull
  fi

  cd ${location}${repo}
  git status

done < ${misc}

# other repos
while read repo; do

  echo ${repo}

  author=$(echo ${repo} | cut -f1 -d/)
  project=$(echo ${repo} | cut -f2 -d/)

  if [ "${clean}" = "clean" ] || [ "${clean}" = "${project}" ]; then
    rm -rf "${location}${project}"
  fi

  if [ ! -d "${location}${project}" ]; then
    cd ${location}
    git clone https://github.com/${author}/${project}.git
  else
    cd ${location}${project}
    git pull
  fi

  cd ${location}${project}
  git status

done < ${other}

# OpenMediaVault
if [ -f "/usr/bin/svn" ]; then
  echo "OpenMediaVault"

  if [ ! -d "${location}${omv_code}" ]; then
    cd ${location}
    svn checkout svn://svn.code.sf.net/p/openmediavault/code/trunk ${omv_code}
  else
    cd ${location}${omv_code}
    svn update
  fi
fi
